name: check html

on: push

jobs:
  run_tidy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install tidy
    - name: run tidy
      run: make tidy
